name: 'latexdiff-action'
description: 'Runs latexdiff whenever a tex file is updated, and pushes the resulting pdf back into the repository.'
inputs:
  file-paths:
    description: 'File paths to run latexdiff on'
    required: true
  git-username:
    description: 'Set git username'
    required: false
    default: 'github-actions[bot]'
  git-email:
    description: 'Set git user email'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  commit-msg:
    description: 'Commit message to use while committing files'
    required: false
    default: 'Update the pdf of ${{ inputs.file-paths }}'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -o latexdiff.zip http://ctan.imsc.res.in/support/latexdiff.zip
        unzip latexdiff.zip
        cd latexdiff
        sudo make install
        cd ..
        sudo apt install texlive-latex-base
        git log -n 1 --skip 1 --pretty=format:"%H" ${{ inputs.file-paths }} | xargs -I{} git show {}:${{ inputs.file-paths }} > old_commit.tex
        yes "" | latexdiff-vc --pdf old_commit.tex ${{ inputs.file-paths }}
        git config user.name ${{ inputs.git-username }}
        git config user.email ${{ inputs.git-email }}
        git add \*.pdf
        git reset latexdiff/*
        git commit -m "${{ inputs.commit-msg }}"
        git pull
        git push
branding:
  icon: 'edit-3'  
  color: 'gray-dark'
